version: "3"

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    expose:
      - 9000
    networks:
      - app_network
    depends_on:
      - db
      - redis
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/wwww/public
    networks:
      - app_network
    depends_on:
      - app
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app_network
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app_network
networks:
  app_network:
