version: "2.3"

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    expose:
      - 9000
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/wwww/public
    networks:
      - app_network
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL",'mysql -u root --database=laravel --password=root --execute="SELECT COUNT(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 10s
      timeout: 10s
      retries: 4
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app_network
networks:
  app_network:
