apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec: #deployment spec
  replicas: 1
  selector: #service spec
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec: #pod spec
      containers:
      - name: mysql-server
        image: mysql:5.7
        args: 
          - "--ignore-db-dir=lost+found"
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
        volumeMounts: #mount volume
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim